services:
  backend:
    # Enable file watching with better performance
    volumes:
      - ./backend/src:/app/src:cached
      - ./backend/package.json:/app/package.json:ro
      - ./backend/tsconfig.json:/app/tsconfig.json:ro
      - ./backend/nodemon.json:/app/nodemon.json:ro
      # Exclude node_modules for better performance
      - /app/node_modules
    environment:
      # Enable polling for file watching in Docker
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      # Increase Node.js memory limit for development
      - NODE_OPTIONS=--max_old_space_size=4096

  frontend:
    # Enable file watching with better performance
    volumes:
      - ./frontend/src:/app/src:cached
      - ./frontend/public:/app/public:cached
      - ./frontend/package.json:/app/package.json:ro
      - ./frontend/tsconfig.json:/app/tsconfig.json:ro
      - ./frontend/tailwind.config.js:/app/tailwind.config.js:ro
      - ./frontend/postcss.config.js:/app/postcss.config.js:ro
      # Exclude node_modules for better performance
      - /app/node_modules
    environment:
      # Enable fast refresh and file watching
      - FAST_REFRESH=true
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true
