services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crypto-dashboard-backend-dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - CORS_ORIGIN=http://localhost:3000
      - MAX_RECONNECT_ATTEMPTS=5
      - RECONNECT_INTERVAL_MS=5000
      - PRICE_HISTORY_HOURS=24
      - HOURLY_AVERAGE_HOURS=48
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json:ro
      - ./backend/tsconfig.json:/app/tsconfig.json:ro
      - ./backend/nodemon.json:/app/nodemon.json:ro
      - ./data:/app/data # SQLite database persistence
    networks:
      - crypto-network
    restart: unless-stopped
    command: npm run start:dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: crypto-dashboard-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3001
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json:ro
      - ./frontend/tsconfig.json:/app/tsconfig.json:ro
      - ./frontend/tailwind.config.js:/app/tailwind.config.js:ro
      - ./frontend/postcss.config.js:/app/postcss.config.js:ro
    depends_on:
      - backend
    networks:
      - crypto-network
    restart: unless-stopped
    command: npm start

networks:
  crypto-network:
    driver: bridge
